plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'fitness.qla.dev.watchlink'
version = '1.0.0'

android {
  namespace 'fitness.qla.dev.watchlink'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'com.google.android.gms:play-services-wearable:20.0.1'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.11.0'
}
